import { WindowStructure } from "../../types/calendarTypes";

const windows: WindowStructure[] = [
  {
    day: 1,
    title: "Pancake Stack",
    teaType: "Black tea",
    brewed: "Perfect with or without milk and even as a lattea",
    ingredients:
      "Calendula, sunflower, jasmine petals, natural flavours and real maple syrup",
    time: 3,
    temperature: 100,
  },
  {
    day: 2,
    title: "Toffee Apple",
    teaType: "Fruit & Herb",
    brewed: "Hot or iced. Add whiskey or honey and lemon for a Toddy",
    ingredients: "Apple & hibiscus, rosehip pieces, natural flavors",
    time: 4,
    temperature: 100,
  },
  {
    day: 3,
    title: "Santas Milk & Cookies",
    teaType: "Black tea",
    brewed: "Perfect with or without milk and even as a lattea",
    ingredients:
      "Sumac berries, cornflower, safflower & red plum petals, natual flavours",
    time: 3,
    temperature: 100,
  },
  {
    day: 4,
    title: "Sweet Ginger",
    teaType: "Rooibos",
    brewed: "Perfect with or without milk and even as a lattea",
    ingredients:
      "Ginger, blackberry leaves, calendula petals, natural flavours",
    time: 5,
    temperature: 95,
  },
  {
    day: 5,
    title: "Candy Cane Popcorn",
    teaType: "Black tea",
    brewed: "Perfect with or without milk and even as a lattea",
    ingredients:
      "Popped rice, apple pieces, white camomile & safflower petals, natural flavours",
    time: 4,
    temperature: 100,
  },
  {
    day: 6,
    title: "Cinnaple Green",
    teaType: "Green tea",
    brewed: "Best hot, no milk",
    ingredients: "Apple pieces, cinnamon, rose & plum petals, natural flavours",
    time: 3,
    temperature: 85,
  },
  {
    day: 7,
    title: "Pumpkin Whoopie",
    teaType: "Black tea",
    brewed: "Perfect with or without milk and even as a lattea",
    ingredients:
      "Apple, orange, rosehip pieces, hibiscus, calendula, sunflower petals, cinnamon, natural flavours",
    time: 4,
    temperature: 100,
  },
  {
    day: 8,
    title: "Apple Crumble",
    teaType: "Fruit & Herb",
    brewed: "Perfect hot or iced",
    ingredients:
      "Elderberry, rosehip & cranbery pieces, hibiscus petals, cinnamon, clove, natural flavours",
    time: 3,
    temperature: 100,
  },
  {
    day: 9,
    title: "Yorkshire Breakfast",
    teaType: "Black tea",
    brewed: "Perfect with a splash of milk",
    ingredients: "Black tea",
    time: 4,
    temperature: 100,
  },
  {
    day: 10,
    title: "Movie Night Popcorn",
    teaType: "Rooibos",
    brewed: "Perfect with or without milk and even as a lattea",
    ingredients: "Pomegranate peel, calendula & plum petals, natural flavours",
    time: 5,
    temperature: 100,
  },
  {
    day: 11,
    title: "Chocolate Cake",
    teaType: "Black tea",
    brewed: "Perfect with or without milk and even as a lattea",
    ingredients: "Cocoa beans, calendula petals, natural flavours",
    time: 3,
    temperature: 100,
  },
  {
    day: 12,
    title: "Morning Maté",
    teaType: "Fruit & Herb",
    brewed: "Perfect hot or iced",
    ingredients:
      "Apple, rosehip, orange pieces, hibiscus, sunflower & safflower petals, rosemary & green maté leaves, natural flavours",
    time: 3,
    temperature: 85,
  },
  {
    day: 13,
    title: "Cookie",
    teaType: "Black tea",
    brewed: "Perfect with or without milk and even as a lattea",
    ingredients:
      "Cornflower, jasmine, rose, calendula petals, natural flavours",
    time: 4,
    temperature: 100,
  },
  {
    day: 14,
    title: "Chocolate Rooibos",
    teaType: "Rooibos",
    brewed: "Perfect with or without milk and even as a lattea",
    ingredients: "Cocoa bean pieces, calendula petals, natural flavours",
    time: 5,
    temperature: 100,
  },
  {
    day: 15,
    title: "Peachy",
    teaType: "Fruit & Herb",
    brewed: "Perfect hot or iced",
    ingredients:
      "Apple, hibiscus, rosehip & peach pieces, camomile petals, natural flavours",
    time: 4,
    temperature: 100,
  },
  {
    day: 16,
    title: "Eggnog",
    teaType: "Black tea",
    brewed: "Perfect with or without milk and even as a lattea",
    ingredients: "Cinnamon, ginger pieces, clove, natural flavours",
    time: 3,
    temperature: 95,
  },
  {
    day: 17,
    title: "Jasmine & Fruits",
    teaType: "Green tea",
    brewed: "Best hot, no milk",
    ingredients: "Jasmine petals, natural flavours",
    time: 2,
    temperature: 85,
  },
  {
    day: 18,
    title: "Everyday Breakfast",
    teaType: "Black tea",
    brewed: "Perfect with a splash of milk",
    ingredients: "Black tea",
    time: 3,
    temperature: 100,
  },
  {
    day: 19,
    title: "Pear Cinnabon",
    teaType: "Rooibos",
    brewed: "Perfect with or without milk and even as a lattea",
    ingredients:
      "Cinnamon, apple & pear pieces, blackberry leaves, safflower & lily flower petals, natural flavours",
    time: 5,
    temperature: 100,
  },
  {
    day: 20,
    title: "Ice Cream Earl Grey",
    teaType: "Black tea",
    brewed: "Perfect with or without milk and even as a lattea",
    ingredients: "Cornflower petals, natural flavours",
    time: 4,
    temperature: 100,
  },
  {
    day: 21,
    title: "Gingerbread",
    teaType: "Black tea",
    brewed: "Perfect with or without milk and even as a lattea",
    ingredients:
      "Ginger, cinnamon, cocoa beans, safflower petals, camomile white flowerss, star anise, natural flavours",
    time: 4,
    temperature: 100,
  },
  {
    day: 22,
    title: "Belly Blue",
    teaType: "Fruit & Herb",
    brewed: "Perfect hot or iced",
    ingredients:
      "Anise, licorice, fennel, currant, rosehip, butterfly blue pea flower, hibiscus, star anise, nettle, jasmine, natural flavours",
    time: 4,
    temperature: 100,
  },
  {
    day: 23,
    title: "Chilly Willy Chai",
    teaType: "Black tea",
    brewed: "Perfect with or without milk and even as a lattea",
    ingredients:
      "Ginger, cinnamon, cardamom, black & white pepper, clove, nutmeg, calendula petals, natural flavours",
    time: 3,
    temperature: 95,
  },
  {
    day: 24,
    title: "Ruby Amaretto",
    teaType: "Rooibos",
    brewed: "Perfect with or without milk and even as a lattea",
    ingredients: "Cornflower, calendula, safflower petals, natural flavours",
    time: 5,
    temperature: 100,
  },
];

export default windows;
